require "app/components/common/animated.rb"
require "app/components/common/position.rb"
require "app/components/common/rotation.rb"
require "app/components/common/size.rb"
require "app/components/common/speed.rb"
require "app/components/common/sprite.rb"
require "app/components/common/visible.rb"
